### ISSUE TITLE
Does not work with Jedi 0.17.0

### ISSUE THREAD

**Issue by pappasam** [pappasam/jedi-language-server#7]
The latest version of Jedi introduces breaking changes to the public API. Starting the language server returns this result:

```console
$ jedi-language-server
Traceback (most recent call last):
  File "/home/sroeca/src/flask-kipauth/.venv/bin/jedi-language-server", line 5, in <module>
    from jedi_language_server.cli import cli
  File "/home/sroeca/src/flask-kipauth/.venv/lib/python3.8/site-packages/jedi_language_server/cli.py", line 5, in <module>
    from .server import SERVER
  File "/home/sroeca/src/flask-kipauth/.venv/lib/python3.8/site-packages/jedi_language_server/server.py", line 37, in <module>
    from .server_utils import (
  File "/home/sroeca/src/flask-kipauth/.venv/lib/python3.8/site-packages/jedi_language_server/server_utils.py", line 10, in <module>
    from jedi.api.classes import Definition
ImportError: cannot import name 'Definition' from 'jedi.api.classes' (/home/sroeca/src/flask-kipauth/.venv/lib/python3.8/site-packages/jedi/api/classes.py)
```

**Comment by pappasam** [comment]
Resolved
